### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by mrceyhun**
@vkuznet @leggerf 

There are differences between production "cms-htcondor-es" in "vocms0240" with upstream repo. Before being so late, I gathered prod version in "refactor" branch. I only selected Readme.md from upstream repo and edited ".gitignore" by including all critical and unnecessary files in it. All other python lines come from production one. After this merge, we can just run pull rebase to implement our changes in production.

Additionally, git user of "cms-htcondor-es" in "vocms0240" is Christian. Should we define a new user or can I set myself as the user?

### CODE REVIEW

**Comment by mrceyhun** [comment]
Could you carefully review?

**Comment by vkuznet** [comment]
the content of PR seems fine to me. Regarding gituser, can you just use dmwm instead?

**Comment by mrceyhun** [comment]
@vkuznet I set "dmwm" as user and removed the user name of Christian. Remote origin is set to https://github.com/dmwm/cms-htcondor-es.git

**Comment by mrceyhun** [comment]
One last thing @vkuznet , Should we squash all 12 commits, "DONOTMERGE" ones look ugly?

**Comment by vkuznet** [comment]
usually I'm neutral to squashing, but in this particular case it would be useful to remove DONOTMERGE in git logs.

**Comment by mrceyhun** [comment]
@vkuznet I removed "DONOTMERGE" keywords with git "reword". There is a conflict in convert_to_json.py, we should choose the lines of "refactor" branch while merging. I compared files with production and they are same. i.e.: `diff -rq $cms_htcondor_cms[refactor branch]/src cms_htcondor_cms[vocms0240]/src`

**Comment by mrceyhun** [comment]
@Valentin Kuznetsov ***@***.***> There are conflicts in this
PR. Changes of the "refactor" branch should be picked in the conflicts.
I can merge it, if I have edit/write right in the master branch.

**Comment by vkuznet** [comment]
I resolved the conflict and will merge the PR.

**Pull request merged**
