### PR TITLE
Update Campaign classad

### LINKED ISSUE #213: Use CMS_CampaignName from WM when available
At present, a job campaign is defined in the following line:

https://github.com/dmwm/cms-htcondor-es/blob/vm-legacy/src/htcondor_es/convert_to_json.py#L699

We have recently implemented a mechanism to report the campaign name in the WM system 
https://github.com/dmwm/WMCore/issues/10914

The class ad name is: `CMS_CampaignName`

When this classad is defined, this information should be used and when not, the current logic in monit can be used instead.
Central services will be updated for next week and this feature will be present.

### PR DESCRIPTION
**Pull request by nikodemas**
`Campaign` field will be filled with `CMS_CampaignName` if it available and if it's not, the current logic will continue to be used as requested in https://github.com/dmwm/cms-htcondor-es/issues/213.

### CODE REVIEW

**Review by leggerf — APPROVED** [review]

**Comment by khurtado** [comment]
@nikodemas 

What happens if the classad value is `classad.classad.Value.Undefined` ? Is this interpreted as `None`, or how is it translated?

**Comment by nikodemas** [comment]
Are you asking about this specific case with `CMS_CampaignName`? Because if it is undefined, then the `ad.get(...)` method returns `None` as you have said and then the code goes through the other `if` branches.

**Comment by khurtado** [comment]
Yes, I was asking about this case. If the request has no campaign fields either at the task/step level or the workload level, we still inject the classad but return `undefined`, which is why I was asking.   If this returns `None` then I think this PR looks good. 
The `m = _camp_re.match(camp)` could potentially be moved a bit lower in the code though, so it doesn't get executed unless we need it.

**Comment by nikodemas** [comment]
So eventually if the `CMS_CampaignName` cannot be guessed based on `WMAgent_RequestName` field in [here](https://github.com/dmwm/cms-htcondor-es/blob/0e915da8af311d6a9c987fa678d8f23552d272be/src/htcondor_es/convert_to_json.py#L1054-L1069), it gets [the same value as `CMS_CampaignType`](https://github.com/dmwm/cms-htcondor-es/blob/0e915da8af311d6a9c987fa678d8f23552d272be/src/htcondor_es/convert_to_json.py#L1070-L1072) (it has a comment from 2021 that it is a temp solution though). And if `CMS_CampaignType` was undefined, then [it would get `UNKNOWN` value](https://github.com/dmwm/cms-htcondor-es/blob/0e915da8af311d6a9c987fa678d8f23552d272be/src/htcondor_es/convert_to_json.py#L1100), so `UNKNOWN` would be assigned to `CMS_CampaignName` then too.

**Comment by nikodemas** [comment]
I have refactored the function to move `m = _camp_re.match(camp)` lower according to your request

**Review by khurtado — APPROVED** [review]
Looking good! Thank you for this.

**Pull request merged**
