### PR TITLE
CRAB_Id is now a string_val

### PR DESCRIPTION
**Pull request by stiegerb**
This is the change for #33

### CODE REVIEW

**Comment by bbockelm** [comment]
So, I don't think we can do this -- the old indices and new ones will not match.  We need to convert the old records, no?

**Comment by stiegerb** [comment]
This would create a new mapping with the next time an index is created. So I guess we'd need to re-index the older data, yes. The alternative would be to change the name of the field?

**Comment by stiegerb** [comment]
@lecriste @cronosnull @bbockelm Note that we still need to fix this before CRAB_Id is really useful. I'll try to get to it later today.

**Comment by stiegerb** [comment]
After some discussion with the es-cms experts (who say it's not worth waiting for a month boundary), I'll just go ahead and merge this now. We should have done it a few months ago, but oh well.

**Pull request merged**
