### PR TITLE
Add logs urls to the document

### PR DESCRIPTION
**Pull request by cronosnull**
**NOT TESTED**
Adding the logs URLs to the document. #90 

Where can I test this change without sending the actual documents?

### CODE REVIEW

**Comment by stiegerb** [comment]
Hi Christian,
You can use the tests/testDocConversion.py script to test the document outputs. It's a bit rough, but should be straightforward to use.

Can you explain a bit more what this is about? Why do you need the WallClock time in seconds? When adding those urls, make sure to protect against non-existing fields. E.g. "Retry" isn't a valid field as far as I can tell. Should those urls work for any job or just analysis jobs?

Cheers,
Benjamin

**Comment by belforte** [comment]
I do not like this.
Code in here should not contain strings like this:  `result['jobLogURL'] = 'https://cmsweb.cern.ch/scheddmon/{sched}/{cmsUserId}/{task}/job.{job}.{retry}.txt'\`
That means that if we ever change the format we report URL's (e.g. not through CMSWEB anymore, which is quite possible) we do not only need to synchronize code change in CRAB and in here, but also need to make the change happen at the same time, something like: drain the grid of crab jobs, do the change, start again, to avoid this code seeing jobs with different URL's.
Sort of .. no way. I am afraid that URL's must be passed as job classAds from CRAB. Every job needs to tell where its logs are to be found.

A possible alternative could be to reuse the job globalId in the URL, so that from CRAB side we may only  need to send the part of the URL which is common to all jobs in a task. But I must say that I like it a lot tha now we have URL's which say immediately which crab_id and retry they refer to.

Indeed these URL's can only work for analysis, atm. Since WMA does not have a convenient way to point to logs. I and many others would like to see that in the future,   but it is not on the radar. Production has to do things differently in any case since they have a policy to save logs 'forever' while in CRAB we delete everything one month after initial submission.

**Comment by belforte** [comment]
BTW, it would be easier for everybody, I presume, if we review and agree on design, before writing code.

**Comment by cronosnull** [comment]
Hi @stiegerb,
These are the URLs showed in the old task monitoring dashboard (for example, this is one of the job logs: https://cmsweb.cern.ch/scheddmon/0196/cms209/190206_001022:tivanov_crab_test_for_DBS_error_2/job_out.3.0.txt). In the current version of the grafana dashboard, I am using a javascript link to create the actual URL, but this is not easy to maintain in the future (it depends of the current position and format of fields in the table). 

The committed wall time is useful in seconds because the duration format in Grafana expects seconds. Grafana let me operate over a field in the query, but that doesn't work if I request for the raw document, which is more efficient because otherwise to show text fields I have to use groupings. Given that using a new index, in which there will be only one document for each job, the groupings are no longer required in the table, it's not worthy to use them only to operate over one field. 

Thanks for the Retry spot! I mistyped it. 

I agree! 
We can still use the javascript links and change them in the future. I'll close this pull request, and, if you agree, I will create one only for the committed wall clock in seconds. 

For the new Index, I'll request to the MONIT group this two fields being added when available.

**Pull request closed without merging**
