### PR TITLE
Try/except'ing document conversion

### PR DESCRIPTION
**Pull request by stiegerb**
I noticed we skip the entire schedd if `convert_to_json` raises an exception. Maybe better to skip only the one offending document.

### CODE REVIEW

**Comment by bbockelm** [comment]
Going to keep this one open for awhile.  I kind of like it when failures are quite visible.  My concern is that, unless there's a feedback mechanism (like an email alert), we might silently drop a whole class of records and insert bias into the dataset.

**Comment by stiegerb** [comment]
Updated this to also fix the underlying problem, which was when we try to apply re.split to fields that are present in the ad but return `classad.Value.Undefined`.

**Comment by stiegerb** [comment]
@bbockelm I also added an email alert for the first exception when converting a document so we'll notice when there's a problem.

**Comment by bbockelm** [comment]
I'm still hot / cold on this one.

I'm a bit reluctant to simply move on past broken records and lose them.

OTOH, there might not be enough buffer space at the schedd to give enough time for the human to intervene.

**Comment by bbockelm** [comment]
Hm -- however, if there's enough time for humans to intervene, they can always reset the checkpoint and resend / reprocess all records.

OK, I think I've convinced myself we can do this.  Merging.

**Pull request merged**
