### PR TITLE
Retain AutoClusterId information

### PR DESCRIPTION
**Pull request by stiegerb**
As discussed in the meeting today (Jan 16)

@bbockelm (if you see this): was there a particular reason for dropping this information?

### CODE REVIEW

**Comment by bbockelm** [comment]
AutoClusterIDs have no long-term meaning: they are reused as needed and may change during the lifetime of the job.

For any given "snapshot" of the condor queue, they are useful for determining what jobs are similar -- but can't be compared across snapshots.

**Comment by stiegerb** [comment]
@bbockelm Ok, makes sense. But I think it still makes sense to use it to track the number of AutoClusters by doing a unique count of Ids.

**Comment by bbockelm** [comment]
Right - so you'd be doing a count of unique IDs versus time, right?

That sounds ... prohibitively expensive if you'd do this in ElasticSearch.  Is this a reasonable thing to do in InfluxDB?

**Comment by belforte** [comment]
can't we get HTC to compute and "print" the relevant number ? So we simply report an integer every 12min ? IIUC the crux is that HTC gives the total number of autoclusters, but not the # of autoclusters for idle jobs, which is what matters. Indeed computing this by looking at all jobs and aggregating their autoclusterId sounds really  last resort.

**Comment by bbockelm** [comment]
Worth noting that the auto-cluster is only unique within a given schedd -- they duplicate across multiple schedds.

If we just want the number of unique auto-clusters, we can simply record this as a separate MONIT record, no?  Don't we need separate MONIT records regardless to replace the aggregates that James and Antonio keep?

**Comment by belforte** [comment]
like: compute the relevant number per-schedd in some script and send this to MONIT ? but do not try to computer the number at ES-query time inside kibana or grafana !

**Comment by aperezca** [comment]
Yes, but then we need to do condor_q queries for each of the schedds from the SI Monit scripts, like

[aperezca@vocms0850 ~]$ condor_q -pool vocms0820 -name crab3@vocms0107.cern.ch -const '(JobStatus == 1)' -af AutoClusterID |sort |uniq |wc -l
125
compared to all:
[aperezca@vocms0850 ~]$ condor_q -pool vocms0820 -name crab3@vocms0107.cern.ch -af AutoClusterID |sort |uniq |wc -l
3337

But having to run additional condor_q queries from the SI monit side is precisely what we wanted to avoid. Maybe it's unavoidable if we want to include "number of autoclusters with idle jobs" as a property of the schedd?

**Comment by stiegerb** [comment]
The performance on ES doesn't seem too bad. This is the number of AutoClusters for the last 7 days for each Schedd, by hour: https://monit-kibana.cern.ch/kibana/app/kibana::/visualize/edit/AWiZMJhZJ0BEWhb4C-yF?_g=(refreshInterval%3A(display%3AOff%2Cpause%3A!f%2Cvalue%3A0)%2Ctime%3A(from%3Anow-7d%2Cmode%3Aquick%2Cto%3Anow))

Only takes a few seconds to load. Over what kinds of time periods do you want to monitor this?

Here's the same in Grafana:
https://monit-grafana.cern.ch/d/nswqKolmk/_user-stiegerb-idle-autoclusterid?orgId=11

**Pull request merged**
