### PR TITLE
Formatted crab id for sort

### LINKED ISSUE #118: Properly sort jobs in Grafana dashboard for task monitoring
Given the discussion in https://github.com/dmwm/CRABServer/issues/5860
we agree with @cronosnull to add a numerical field corresponding to the `CRAB_Id` string and sort jobs accordingly.

At the moment, the possible values of CRAB_Id are of two types:
- "1", "2", "3", ..., up to ~"10000"
- "n-1", "n-2", "n-3", ..., where n can be 0, 1, 2 or 3

and the overall order should be 0-1, 0-2, 0-3, 0-..., 1, 2, 3, ..., 1-1, 1-2, 1-3, 1-..., 2-1, 2-2, 2-3, 2-..., 3-1, 3-2, 3-3, 3-...

### PR DESCRIPTION
**Pull request by cronosnull**
Given the sorting limitation in grafana (that only sort as numerical values that are numerical in ES, even if the strings only contains numbers) and that now we have some non-only numerical CRAB_Ids, we create a new field with the formatted representation of the crab id for sorting. 

Closes #118

### CODE REVIEW

**Comment by stiegerb** [comment]
Looks good to me, but maybe this is a bit more readable/pythonic?
```python
result['FormattedCrabId'] = 0 # Or whatever default value?
try:
   result['FormattedCrabId'] = "{:06d}".format(int(_cid))
except TypeError:
   try:
      result['FormattedCrabId'] = "{}.{:06d}".format(*[int(x) for x in _cid.split("-")])
   except TypeError:
      pass # Fall back to default
```

Did you test it?

**Comment by cronosnull** [comment]
Yes, I tested it whit some documents. I prefer to no use exceptions in this case (is not required as the cases can be controlled)

**Comment by stiegerb** [comment]
That's what I meant by "pythonic". There's something about better asking for forgiveness than for permission :)

But it doesn't make a difference. Last comment: you're not controlling the default value now. Maybe make sure it's something useful.

**Comment by cronosnull** [comment]
It is the CRAB_Id value (It should not happen, but just in case)

**Comment by belforte** [comment]
now now.. this
`It should not happen, but just in case`
 conflicts with 
` the cases can be controlled`

guess I am bikeshedding here.. sorry. will stop.

**Comment by stiegerb** [comment]
That was my point and why I was generally following the strategy of "first set it to some reasonable default, then try to change it within some constraints".

**Comment by belforte** [comment]
+1

**Comment by cronosnull** [comment]
I added documentation, make it a separated function and managed exceptions. 
Thanks for the comments :1st_place_medal:

**Comment by belforte** [comment]
so grafana sorting is lexicographic, not numeric ?

**Comment by cronosnull** [comment]
In this case, it is because in ES that field is a String, then is sorted as a string in grafana.

**Comment by stiegerb** [comment]
@cronosnull The default is still whatever is written into CRAB_Id. I meant to change that to something you control. I.e. set it to "0" and then try to change it from what's in CRAB_Id, but only if that makes sense.

**Comment by cronosnull** [comment]
In case the CRAB_Id doesn't follow the expected patterns, I was thinking of leaving it to see it in grafana (and use it to sort). Do you think is necessary to set a fixed default value in this case?

**Comment by belforte** [comment]
I agree with @cronosnull here. If we introduce some bug in CRAB and write an oddily formatted CRAB_Id, better to see what it is.

**Comment by stiegerb** [comment]
Well, we have the actual CRAB_Id as a field, right? So we can always debug using the original, anyway. Since we're introducing this field for sorting, I would make sure it never breaks.

**Comment by belforte** [comment]
that's a good point. Nothing wrong with `000000`. Anyhow I do not believe we'll ever see that. But if today we want to write unbreakable code.. go for it !

**Pull request merged**
