### PR TITLE
Fixing race condition with updating the checkpoint file

### PR DESCRIPTION
**Pull request by stiegerb**
There's currently a race condition in `process_histories` where several `process_schedd` processes might open and write to the same checkpoint file at the same time. This could lead to a missed update and later to duplicate data.

We also currently update the checkpoint even in cases where the job loop runs into a timeout and in any case update the checkpoint file again at the end for no reason as far as I can tell.

To fix this I added a dedicated process that reads from a queue and then updates the checkpoint file. This only happens if the job loop finishes without timing out, i.e. only then the checkpoint gets updated.

Note that in case the job loop times out, those jobs that are already processed (and uploaded) will be processed and uploaded again the next time the script is run, so there is still potential for duplicate data in cases where the script times out. Only way to solve that would be to keep track of what was already uploaded, e.g. by ordering the list of jobs by their `EnteredCurrentStatus` date.

### CODE REVIEW

**Comment by belforte** [comment]
IIUC the queue is in memory what happens if the queue is lost ? e.g. process crash or machine reboot. Do we loose events then ? Or simply restart from last saved checkpoint and possibly get a fee duplicates ? Simply to point out that you want to be protected also against unpredictable events (power cord is pulled) which may happen at different times (and places in the code) then standard things like a process times out

**Comment by stiegerb** [comment]
@belforte The way it works is that there is a checkpoint file containing the name of each schedd and the last completion date. This file only gets opened and updated when a history loop finishes correctly. So if the entire thing would crash, nothing would get updated and the next time the script ran it would start again from the same checkpoint (possibly leading to some duplication).

If the script doesn't find or cannot open the checkpoint file, it takes by default the last 12h of jobs from each schedd, so that would be the worst case scenario (we completely lose the checkpoint). In other words, unless we completely lose the checkpoint file and not fix the situation within 12h we won't lose any data. All other cases might lead to some duplication at worst.

Note that all of this is already in place before this PR.

The queue here is just a technicality to ensure there is only one process that opens and writes to the checkpoint file. I.e. instead of each job loop updating the file itself (which is what is happening now), they send an event to the queue, and a separate process takes care of it.

**Comment by bbockelm** [comment]
Note that there is duplicate detection on the ElasticSearch side too -- you don't end up with multiple DB entries but rather just a bit of unnecessary data being sent.

**Comment by stiegerb** [comment]
@bbockelm Yes, but that is only true for ES, not for the MONIT infrastructure. So in InfluxDB and HDFS we *will* end up with duplication. I'm trying to get MONIT to run some kind of duplicate detection on HDFS in the context of completing the archival job data, see [RQF1088156](https://cern.service-now.com/service-portal/view-request.do?n=RQF1088156).

**Comment by belforte** [comment]
got it. Thanks. Sorry if I thought that the queue was a data fifo :-(

**Pull request merged**
