### PR TITLE
add CRAB_Workflow to list of Important Attributes

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by bbockelm** [comment]
Are we sure we want folks looking there?  The "human readable" part of the `CRAB_Workflow` is already copied to `Workflow` (system neutral attribute so we can use the same attribute name for WMAgent).

**Comment by belforte** [comment]
sorry I only meant to document something that's there already
and that I would use. I was not aware of this unified Workflow.
So now we have CRAB_Workflow, CRAB_ReqName and Workflow all
meaning same thing in slightly different ways :-(

OTOH I'd rather you do not drop the initial timestamp from the crab task name, I suspect you loose unicity i.e. "dpitzl_crab_V0_2016G" can refer to multiple tasks. If you record bare ClassAds I can always dig my source code and figure out what they exactly are, as soon as you start manipulating the needed digging increase. Also I'd like to go to job stdout and do not
be surprised by finding different stuff in the ClassAds listed there vs. ES.

**Comment by bbockelm** [comment]
I captured the knowledge from your comment above and added it to the branch.  Merging the PR.

**Comment by belforte** [comment]
perfect. thanks

**Pull request merged**
